apiVersion: apps/v1
kind: Deployment
metadata:
  name: neometrobackend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neometrobackend
  template:
    metadata:
      labels:
        app: neometrobackend
    spec:
      containers:
      - name: neometrobackend
        image: tvarun2014/neometrobackend:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 4000
        envFrom:
         - secretRef:
              name: backend-env

---
apiVersion: v1
kind: Service
metadata:
  name: neometrobackend-service
spec:
  type: NodePort
  selector:
    app: neometrobackend
  ports:
  - port: 4000
    targetPort: 4000
    nodePort: 30020
