const stations = {
    1: "Miyapur",
    2: "Jntu",
    3: "Kphb Colony",
    4: "Kukatpally",
    5: "Balanagar",
    6: "Moosapet",
    7: "Bharath Nagar",
    8: "Erragadda",
    9: "Esi Hospital",
    10: "Sr Nagar",
    11: "Ameerpet",
    12: "Panjagutta",
    13: "Irrum Manzil",
    14: "Khairatabad",
    15: "Lakdikapol",
    16: "Assembly",
    17: "Nampally",
    18: "Gandhi Bhavan",
    19: "Osmania Medical College",
    20: "Mg Bus Station",
    21: "Malakpet",
    22: "New Market",
    23: "Musarambhag",
    24: "Dilsukhnagar",
    25: "Chaitanyapuri",
    26: "Victoria Memorial",
    27: "Lb Nagar",
    28: "Raidurg",
    29: "Hitec City",
    30: "Durgam Cheruvu",
    31: "Madhapur",
    32: "Peddamma Gudi",
    33: "Jubilee Hills Check Post",
    34: "Road No5 Jubilee Hills",
    35: "Yusufguda",
    36: "Madhura Nagar",
    37: "Ameerpet",
    38: "Begumpet",
    39: "Prakash Nagar",
    40: "Rasoolpura",
    41: "Paradise",
    42: "Parade Ground",
    43: "Secunderabad East",
    44: "Mettuguda",
    45: "Tarnaka",
    46: "Habsiguda",
    47: "Ngri",
    48: "Stadium",
    49: "Uppal",
    50: "Nagole",
    51: "Parade Ground",
    52: "Secunderabad West",
    53: "Gandhi Hospital",
    54: "Musheerabad",
    55: "Rtc X Roads",
    56: "Chikkadpally",
    57: "Narayanaguda",
    58: "Sulthan Bazaar",
    59: "Mg Bus Station"
  };
  